# Generated by Django 5.1.3 on 2024-12-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactFullName', models.CharField(max_length=50)),
                ('contactEmail', models.CharField(max_length=50)),
                ('contactPhoneNumber', models.IntegerField()),
                ('contactSubject', models.CharField(max_length=50)),
                ('contactMessage', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
